/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_hello_FibLib */

#ifndef _Included_org_example_hello_FibLib
#define _Included_org_example_hello_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_hello_FibLib
 * Method:    fibN
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_example_hello_FibLib_fibN
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_example_hello_FibLib
 * Method:    fibNI
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_example_hello_FibLib_fibNI
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
