/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_hello_MatchLib */

#ifndef _Included_org_example_hello_MatchLib
#define _Included_org_example_hello_MatchLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_hello_MatchLib
 * Method:    matching
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_hello_MatchLib_matching
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
